server:
  port: 9902

spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: root
    username: root
    virtual-host: /
  data:
    mongodb:
      user: root
      password: root
      uri: mongodb://localhost:27017/ecomapp-attachments

queue:
  attachment:
    name: AttachmentQueue


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: staging
  rabbitmq:
    host: rabbit
  data:
    mongodb:
      uri: mongodb://user1:user1@mongo:27017/test?authSource=admin&authMechanism=SCRAM-SHA-1

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
