server:
  port: 9901

spring:
  servlet:
    multipart:
      maxFileSize: 1MB
      max-request-size: 10MB
  rabbitmq:
    host: rabbit
    port: 5672
    password: root
    username: root
    virtual-host: /
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/ecomapp
    username: postgres
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL94Dialect
  main:
    allow-bean-definition-overriding: true
queue:
  attachment:
    name: AttachmentQueue

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: staging
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://postgres:5432/ecomapp
    username: postgres
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL94Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
