server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: file://${user.dir}/..
          search-paths:
          - config-repo

---
spring:
  profiles:
    active: staging, prod
  cloud:
    config:
      label: cart-service
      server:
        git:
          uri: https://github.com/zios07/ecommerce-app
          username: zios07
          password:
          force-pull: true
          search-paths:
          - config-repo
